// Static mentor directory used as a stand-in for the live backend (#861/#863).
import type { Mentor } from "@/types/mentor";

export const MENTOR_DIRECTORY: Mentor[] = [
  {
    id: "amara-okafor",
    name: "Amara Okafor",
    title: "Senior Full-Stack Engineer",
    bio: "Full-stack engineer passionate about teaching scalable system design.",
    avatarUrl: "/avatars/alex.svg",
    industry: "Fintech",
    skills: [
      { id: "frontend", name: "Frontend" },
      { id: "backend", name: "Backend" },
      { id: "nodejs", name: "Node.js" },
      { id: "nextjs", name: "Next.js" },
      { id: "postgres", name: "PostgreSQL" },
    ],
    rating: 4.9,
    reviewCount: 124,
    hourlyRate: 85,
    experienceLevel: "senior",
    availability: "available",
    isFeatured: true,
    popularity: 92,
  },
  {
    id: "jane-smith",
    name: "Jane Smith",
    title: "UX/UI Designer",
    bio: "Creates beautiful and intuitive user experiences.",
    avatarUrl: "/avatars/jane.svg",
    industry: "E-Commerce",
    skills: [
      { id: "ui-ux", name: "UI/UX" },
      { id: "figma", name: "Figma" },
      { id: "design-systems", name: "Design Systems" },
      { id: "research", name: "User Research" },
    ],
    rating: 4.8,
    reviewCount: 98,
    hourlyRate: 70,
    experienceLevel: "mid",
    availability: "available",
    isFeatured: false,
    popularity: 77,
  },
  {
    id: "john-doe",
    name: "John Doe",
    title: "Software Engineer",
    bio: "Specializes in frontend development and React.",
    avatarUrl: "/avatars/john.svg",
    industry: "EdTech",
    skills: [
      { id: "frontend", name: "Frontend" },
      { id: "react", name: "React" },
      { id: "typescript", name: "TypeScript" },
      { id: "testing", name: "Testing" },
    ],
    rating: 4.5,
    reviewCount: 60,
    hourlyRate: 55,
    experienceLevel: "junior",
    availability: "busy",
    isFeatured: false,
    popularity: 61,
  },
  {
    id: "sarah-wilson",
    name: "Sarah Wilson",
    title: "Data Scientist",
    bio: "Expert in machine learning and data visualization.",
    avatarUrl: "/avatars/sarah.svg",
    industry: "AI / Machine Learning",
    skills: [
      { id: "backend", name: "Backend" },
      { id: "python", name: "Python" },
      { id: "ml", name: "Machine Learning" },
      { id: "data-viz", name: "Data Visualization" },
    ],
    rating: 4.7,
    reviewCount: 143,
    hourlyRate: 95,
    experienceLevel: "senior",
    availability: "available",
    isFeatured: true,
    popularity: 88,
  },
  {
    id: "michael-chen",
    name: "Michael Chen",
    title: "Backend Engineer",
    bio: "Builds scalable APIs and resilient microservices.",
    avatarUrl: "/avatars/alex.svg",
    industry: "SaaS",
    skills: [
      { id: "backend", name: "Backend" },
      { id: "devops", name: "DevOps" },
      { id: "go", name: "Go" },
      { id: "aws", name: "AWS" },
      { id: "kubernetes", name: "Kubernetes" },
    ],
    rating: 4.6,
    reviewCount: 87,
    hourlyRate: 90,
    experienceLevel: "senior",
    availability: "busy",
    isFeatured: false,
    popularity: 70,
  },
  {
    id: "emily-davis",
    name: "Emily Davis",
    title: "Product Manager",
    bio: "Drives product strategy and cross-functional team alignment.",
    avatarUrl: "/avatars/jane.svg",
    industry: "Fintech",
    skills: [
      { id: "product-management", name: "Product Management" },
      { id: "strategy", name: "Strategy" },
      { id: "roadmapping", name: "Roadmapping" },
      { id: "analytics", name: "Analytics" },
    ],
    rating: 4.9,
    reviewCount: 210,
    hourlyRate: 75,
    experienceLevel: "principal",
    availability: "available",
    isFeatured: false,
    popularity: 95,
  },
  {
    id: "david-kim",
    name: "David Kim",
    title: "DevOps Engineer",
    bio: "Automates cloud infrastructure and streamlines CI/CD pipelines.",
    avatarUrl: "/avatars/john.svg",
    industry: "Cybersecurity",
    skills: [
      { id: "devops", name: "DevOps" },
      { id: "backend", name: "Backend" },
      { id: "docker", name: "Docker" },
      { id: "terraform", name: "Terraform" },
    ],
    rating: 4.4,
    reviewCount: 54,
    hourlyRate: 100,
    experienceLevel: "mid",
    availability: "unavailable",
    isFeatured: false,
    popularity: 58,
  },
  {
    id: "ife-adeniyi",
    name: "Ife Adeniyi",
    title: "Frontend Engineer",
    bio: "Loves crafting accessible, performant interfaces with React.",
    avatarUrl: "/avatars/alex.svg",
    industry: "HealthTech",
    skills: [
      { id: "frontend", name: "Frontend" },
      { id: "react", name: "React" },
      { id: "javascript", name: "JavaScript" },
      { id: "css", name: "CSS" },
    ],
    rating: 4.7,
    reviewCount: 41,
    hourlyRate: 60,
    experienceLevel: "junior",
    availability: "available",
    isFeatured: false,
    popularity: 64,
  },
  {
    id: "priya-sharma",
    name: "Priya Sharma",
    title: "UI/UX Designer",
    bio: "Designs product experiences that feel effortless.",
    avatarUrl: "/avatars/sarah.svg",
    industry: "SaaS",
    skills: [
      { id: "ui-ux", name: "UI/UX" },
      { id: "figma", name: "Figma" },
      { id: "prototyping", name: "Prototyping" },
      { id: "accessibility", name: "Accessibility" },
    ],
    rating: 4.8,
    reviewCount: 76,
    hourlyRate: 80,
    experienceLevel: "mid",
    availability: "available",
    isFeatured: false,
    popularity: 71,
  },
];